apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: daniel-lopez-fisag-dev
  labels:
    app: backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image: danielopezh/comments-backend-api:{{ tag }}
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: BACKEND_DATA_URL
          value: "http://backend-data:80"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api
  namespace: daniel-lopez-fisag-dev
  labels:
    app: backend-api
spec:
  selector:
    app: backend-api
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: backend-api
  namespace: daniel-lopez-fisag-dev
  labels:
    app: backend-api
spec:
  host: backend-api-daniel-lopez-fisag-dev.apps.sandbox-m4.g2pi.p1.openshiftapps.com
  to:
    kind: Service
    name: backend-api
  port:
    targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-api
  namespace: daniel-lopez-fisag-dev
  labels:
    app: backend-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-api
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
